server:
  port: 8282
  servlet: 
    context-path: /api/dev
---
spring:
    profiles: dev
    data:
      mongodb:
        host: localhost
        port: 27017
        database: estore
        repositories:
          type: auto
